# Generated by Django 5.1.2 on 2024-11-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0002_alter_usermodels_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodels',
            name='userid',
            field=models.IntegerField(auto_created=True, default=0),
        ),
        migrations.AlterField(
            model_name='usermodels',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
