# Generated by Django 5.1.1 on 2024-11-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0003_usermodels_userid_alter_usermodels_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(auto_created=True, default=0)),
            ],
        ),
    ]
