# Generated by Django 5.1.1 on 2024-11-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0004_logstorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logstorage',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
